#!/bin/bash

# Reading user input 

read -p "Enter your name: " myName;
read -p "Enter your town: " mytown;
read -p "Enter you street: " mystreet;

echo "My name is $myName " ;
echo "The street I grew up on was $mystreet and the town was $mytown."
