#!/bin/bash

# example

if [ -z $1 ]; then 
    read -p "Enter the dirname: " dir;
else 
    dir=$1;
fi

directories=0;
files=0;

if [ -d $dir ]; then

    echo -e "Listing files in $dir";
    echo "--------------------- "

    for filename in `ls $dir`; do

        # checking if its a directory
        if [ -d "$dir/$filename" ] ; then
            echo "(D) $filename";
            let directories=$directories+1; # increment directories
            
        else
            echo -e "$filename";
            let files=$files+1;
        fi
    done

    echo -e "\n---- SUMMARY -----";
    echo "Files: $files";
    echo "Directories: $directories";
    echo "-------- done -------- ";

elif [ -f $dir ]; then
    echo "It seems that $dir is a regular file.";
else 
    echo "No such file or directory";
fi

